{
  "San Francisco": {"Los Angeles": 100, "Salt Lake City": 156, "Portland": 151},
  "Portland": {"San Francisco": 151, "Salt Lake City": 175, "Seattle": 44},
  "Seattle": {"Portland": 44, "Vancouver": 45, "Calgary": 118, "Helena": 189},
  "Vancouver": {},
  "Los Angeles": {},
  "Las Vegas": {},
  "Calgary": {},
  "Salt Lake City": {},
  "Phoenix": {},
  "Helena": {},
  "Denver": {},
  "Santa Fe": {},
  "El Paso": {},
  "Winnipeg": {},
  "Duluth": {},
  "Omaha": {},
  "Oklahoma City": {},
  "Kansas City": {},
  "Dallas": {},
  "Houston": {},
  "Little Rock": {},
  "Saint Louis": {},
  "Sault Ste Marie": {},
  "New Orleans": {},
  "Chicago": {},
  "Nashville": {},
  "Toronto": {},
  "Pittsburgh": {},
  "Atlanta": {},
  "Montreal": {},
  "Miami": {},
  "Charleston": {},
  "Raleigh": {},
  "New York": {},
  "Washington": {},
  "Boston": {}
}
